[build]
command = "npm run build"
publish = "dist"
functions = "functions"

[dev]
command = "eleventy --serve"

[[plugins]]
package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
  performance = 0.5
  accessibility = 0.5
  best-practices = 0.5
  seo = 0.5
  pwa = 0.1

  [[plugins.inputs.audits]]
    path = "index.html"

[[plugins]]
package = "netlify-plugin-11ty"

  [plugins.inputs]
  cache_img = [ "./images", "./img" ]
  cache_assets = "../.cache"
